syntax on
set number
set relativenumber
set autoindent
set smartindent

" автоперенос
" set nowrap 
set shiftwidth=4
set ttimeoutlen=0
set splitright
set splitbelow
" Позволяет переходить на другю вкладку без сохранения
set hidden
" Игнорировать регистр при поиске.
" Для поиска с учетом регистра, нужно поместить \C в любое место искомой строки
set ignorecase
" подсвечивать все совпадения при поиске
set hlsearch
" подсвечивать совпадение во время поиска на лету
set incsearch
" выделять строку, на которой находится курсор
set cursorline
" количество cтрок в всплывающем окне
set pumheight=5
" количество строк вокруг курсора при прокрутке
set scrolloff=5

" отступы
autocmd FileType python setlocal ts=4 sts=4 sw=4 et
autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noet
autocmd FileType html setlocal ts=2 sts=2 sw=2 noet
autocmd FileType htmldjango setlocal ts=2 sts=2 sw=2 noet
autocmd FileType css setlocal ts=2 sts=2 sw=2 noet

command! Vimrc :vs $MYVIMRC
" copy to buffer
vmap <F2> "+y

nmap fl :bn<cr>
nmap fh :bp<cr>

" toggle paste mode
nmap fp :set paste<cr>
nmap fpp :set nopaste<cr>


" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" подсветка синтаксиса в i3config 
Plug 'mboughaba/i3config.vim'
aug i3config_ft_detection
  au!
  au BufNewFile,BufRead ~/.config/i3/config set filetype=i3config
aug end

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
let NERDTreeWinSize = 20
map <F3> :NERDTreeToggle<CR>


" markdown preview
Plug 'JamshedVesuna/vim-markdown-preview'
let vim_markdown_preview_github=1
" let vim_markdown_preview_hotkey='<C-p>'

Plug 'morhetz/gruvbox'
let g:indent_guides_auto_colors = 0
let g:indent_guides_enable_on_vim_startup = 1
let g:gruvbox_contrast_dark="hard"
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4

" Вместо 'c-n' 'tab'
Plug 'ervandew/supertab'

Plug 'szw/vim-tags'
Plug 'majutsushi/tagbar'
let g:tagbar_sort = 0
map <F5> :TagbarToggle<CR>

" подсветка парных скобок
Plug 'amdt/vim-niji' 
let g:niji_dark_colours = 1
let g:niji_matching_filetypes = ['python', 'javascript', 'json', 'julia', 'jl']
let g:niji_matching_characters = [['(', ')'],
                                     \ ['\[', '\]'],
                                     \ ['{', '}']]

" восстановление последней позиции в файле
Plug 'farmergreg/vim-lastplace'
let g:lastplace_ignore = "gitcommit,gitrebase,svn,hgcommit"
let g:lastplace_open_folds = 0

Plug 'vim-airline/vim-airline', {'for': ['python', 'julia', 'javascript', 'json', 'cpp', 'c', 'html', 'htmldjango' ] }
Plug 'vim-airline/vim-airline-themes', {'for': ['python', 'julia', 'javascript', 'json', 'cpp', 'c', 'html', 'htmldjango' ] }
let g:airline_theme='solarized' " raven_blue
let g:airline_solarized_bg = 'dark'
let g:airline_left_sep = ''
let g:airline_fugitive_prefix = '∲'
let g:airline_right_sep = ''
let g:airline_powerline_fonts = 1
let g:airline#extensions#keymap#enabled = '0'
let g:airline#extensions#xkblayout#enabled = '0'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#tab_min_count = 2
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#show_buffers = 1
let g:airline#extensions#tabline#show_tab_nr = 1

" Documentation
Plug 'Keithbsmiley/investigate.vim'
nnoremap <F1> :call investigate#Investigate()<CR>

" Change lang to EN in Normal
Plug 'lyokha/vim-xkbswitch'
let g:XkbSwitchEnabled       = 1
let g:XkbSwitchLib           = '/usr/local/lib/libxkbswitch.so'
let g:XkbSwitchIMappings     = ['ru']
let g:XkbSwitchSkipIMappings = {'*' : ['[', ']', '{', '}', "'"]}

" перемещение текущей строки или выделенных строк вверх или вниз
Plug 'matze/vim-move'
let g:move_key_modifier = 'C'

" комментирование выделенных строк
Plug 'tomtom/tcomment_vim'

" HTML/XML audoclosing tags
Plug 'tpope/vim-surround', {'for': ['htmldjango','html', 'xml']}

" Plugun for fast creating tags
Plug 'mattn/emmet-vim',           { 'for': ['htmldjango', 'html', 'css'] }

" Подсветка парных тегов
Plug 'gregsexton/MatchTag'

Plug 'hail2u/vim-css3-syntax',    { 'for': ['htmldjango', 'html','css'] }
augroup VimCSS3Syntax
  autocmd!
  autocmd FileType css setlocal iskeyword+=-
augroup END

Plug 'pangloss/vim-javascript',      { 'for': 'javascript' }
let g:javascript_plugin_jsdoc = 1

Plug 'othree/html5.vim', {'for': ['htmldjango', 'html']}

" Отображение линий отступов
Plug 'Yggdroot/indentLine'
let g:indentLine_char       = '¦'
let g:indentLine_color_term = 239
let g:indentLine_color_gui  = '#A4E57E'

Plug 'Chiel92/vim-autoformat'
let g:formatprg_args_javascript = "-j -q -B -f -"
noremap  <F8>   :Autoformat<CR><CR>
vnoremap <C-F8> gq

Plug 'lervag/vimtex', {'for': 'tex'}
let g:tex_flavor='latex'
let g:tex_conceal='abdmg'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0

augroup Tex
    autocmd!
    autocmd FileType *.tex set conceallevel=1
    autocmd FileType *.tex set concealcursor=c
augroup END

let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-shell-escape',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \   '-jobname="string"'
      \ ],
      \}

inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>
nnoremap <buffer> <F10> :exec '!pdflatex -shell-escape' shellescape(@%, 1)<cr>


Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-c-f>"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips', 'UltiSnips']
let g:UltiSnipsEditSplit="vertical"

nmap <F7> :setlocal spell<cr>
vmap <F7> <esc>:setlocal spell<cr>i
imap <F7> <esc>:setlocal spell<cr>i
" setlocal spell
set spelllang=en_us,ru_ru
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

" cpp syntax
Plug 'octol/vim-cpp-enhanced-highlight', {'for': 'cpp'} 
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_experimental_simple_template_highlight = 1

" julia
Plug 'JuliaEditorSupport/julia-vim', {'for': 'julia'}
let g:latex_to_unicode_auto = 1
autocmd BufRead,BufNewFile *.jl :set filetype=julia

" python
nnoremap <buffer> <F9> :exec '!python3' shellescape(@%, 1)<cr>
" au FileType *.py nnoremap <buffer> <F9> :!python3 % <cr>

Plug 'davidhalter/jedi-vim', {'for': 'python'}

" Plug 'klen/python-mode', {'for': 'python'}

let g:jedi#auto_vim_configuration = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#popup_on_dot = 1
let g:jedi#force_py_version = 3
let g:jedi#popup_select_first = 0


call plug#end()
" end plugins

set background=dark
set termguicolors
colorscheme gruvbox
set t_Co=256

set conceallevel=1
set concealcursor=c
:setlocal spell 
:hi SpellBad cterm=underline,italic 

