#! /bin/sh

sxhkd &
xkbcomp /home/slava/.config/xkbcomp/stru $DISPLAY && xcape -e "ISO_Level3_Shift=Escape" &
python3 /home/slava/builds/inkscape-shortcut-manager/main.py &
/home/slava/.config/bspwm/extremal_rules.sh &
$HOME/.config/polybar/launch.sh &
nitrogen --restore

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Inkscape desktop='^2' follow=on
bspc rule -a Firefox desktop='^3'
bspc rule -a Vivaldi desktop='^3'
bspc rule -a URxvt state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
